### DISCUSSION TITLE
What if a plugin take some custom parameter for the user?

### DISCUSSION THREAD

**Discussion by vincenzopalazzo** [coffee-tools/coffee#140] [Ideas]
In the following bug report https://github.com/coffee-tools/coffee/issues/138 we have a request to support a custom parameter from the user

This can be included inside the [coffee manifest](https://coffee-docs.netlify.app/support-coffee.html) as discussed in https://github.com/coffee-tools/coffee/issues/138#issuecomment-1565883539, but we also need a way to use the coffee input parameters inside the manifest script itself.

An example, let the imagine have the following manifest 

```yml
plugin:
  name: btcli4j
  version: 0.0.1
  lang: java
  install: |
    # the path is a coffee rules that bind the input value inside the script
    sh -C ${path}/gradlew createRunnableScript
  # we should add this field, and ask to the user to insert it
  input:
      - path: 
           - required: true
           - type: string
           - description: "patch of the gradel script"
  main: btcli4j-gen.sh
```

This looks like duable, but also we should take into count how these input parameters will look like inside the web and the plugin
